### ISSUE TITLE
Can not receive messages on latest develop version

### ISSUE THREAD

**Issue by nishimaki10** [RocketChat/hubot-rocketchat#111]
0.26.0: OK
develop: NG

```
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Starting Rocketchat adapter...
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Once connected to rooms I will respond to the name: ws
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Connecting To: rocketchat:3000
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Successfully connected!
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO general
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Logging In
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Successfully Logged In
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Looking up Room ID for: general
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Joining Room: GENERAL
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO rid:  [ 'GENERAL' ]
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO All rooms joined.
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Successfully joined room: GENERAL
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Preparing Meteor Subscriptions..
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Subscribing to Room: GENERAL
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO All subscriptions ready.
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Successfully subscribed to room: GENERAL
hubot_1 | [Thu Apr 14 2016 15:41:51 GMT+0900 (JST)] INFO Setting up reactive message list...
hubot_1 | Server misbehaviour: item id doesn't exist
hubot_1 | Server misbehaviour: item id doesn't exist
```

**Comment by mikkeschiren** [comment]
We have the same problem.

**Comment by clegault** [comment]
We have the same problem as well.

**Comment by geekgonecrazy** [comment]
Sorry about this guys!  Please stick the latest release instead of develop.  We switched some stuff with how messages are delivered in the develop branch.

We'll try and get this fixed before these changes make it into 0.27.0

**Comment by tholu** [comment]
Same problem here.

**Comment by tholu** [comment]
@geekgonecrazy Was this fixed in the newly released 0.27.0? https://github.com/RocketChat/Rocket.Chat/releases/tag/0.27.0

**Comment by Sing-Li** [comment]
Please cautiously test the 0.27.0 that was cut late last night.

Meanwhile, for important production system, please stay with 0.26.0 until the trailbrailzers all report success.

For all those who have production systems, please consider switching to our release stable builds only moving forward.  Likelihood of continued problems with latest develop build is 100%.

**Comment by clegault** [comment]
Thanks for the response Sing-Li. Perhaps the install docs for heroku should be updated to reflect that advice. If you follow the directions to set up a heroku instance of rocket.chat you will get the developer branch because it is the default branch. (this is what I did unfortunately)

For my own instance, I updated the code between 0.26 and 0.27 and my hubot stopped working. I tried to rollback to 0.26 and rocket.chat would only crash after that so I had to go back to the in between code base. I can't speak for everyone, but for me I am stuck going forward until the next release rests on stable.

**Comment by clegault** [comment]
FYI I have tested 0.27.0 now and this adapter is still broken.

**Comment by tholu** [comment]
@clegault 0.27.0 works for me though.

**Comment by clegault** [comment]
@tholu the chat works for me, but my hubot cannot connect.

**Comment by clegault** [comment]
Sorry for the false report, someone removed the rocket.chat adapter from our startup script while troubleshooting it when it stopped working and neglected to put it back in. To be clear, I have verified that the **hubot adapter does indeed work again in 0.27.0.** Sorry for the confusion.

**Comment by nishimaki10** [comment]
0.27.0 works! Thanks!

**Comment by Sing-Li** [comment]
Thanks for confirming.  Closing the issue now.
